#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# pre-processing 
runApplication blockMesh
runApplication topoSet
runApplication refineMesh -overwrite
runApplication checkMesh
runApplication setFields

# run in parallel
runApplication decomposePar -cellDist
runParallel $(getApplication)
runApplication reconstructPar

#------------------------------------------------------------------------------