#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Compile OpenFOAM libraries and applications
wmake $targetType fvModels/derived/laserDTRM

wmake $targetType meshTools/sets/cellSources/spheresToCell

wmake $targetType OpenFOAM/primitives/functions/ErrorFunction

wmake $targetType physicalProperties

wmake $targetType twoPhaseModels/interfaceThermoProperties

wmake $targetType twoPhaseModels/immiscibleIncompressibleTwoPhaseThermoMixture

wmake $targetType twoPhaseModels/twoPhaseChange